const ContactAction = {
    FETCH_CONTACTS: 'FETCH_CONTACTS',
    FETCH_CONTACTS_SUCCESS: 'FETCH_CONTACTS_SUCCESS',
    FETCH_CONTACTS_ERROR: 'FETCH_CONTACTS_ERROR',
    ADD_CONTACT: 'ADD_CONTACT',
    ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
    ADD_CONTACT_ERROR: 'ADD_CONTACT_ERROR',
    DELETE_CONTACT: 'DELETE_CONTACT',
    DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
    DELETE_CONTACT_ERROR: 'DELETE_CONTACT_ERROR',
    EDIT_CONTACT: 'EDIT_CONTACT',
    EDIT_CONTACT_SUCCESS: 'EDIT_CONTACT_SUCCESS',
    EDIT_CONTACT_ERROR: 'EDIT_CONTACT_ERROR',
    SEARCH_CONTACT: 'SEARCH_CONTACT',
    SEARCH_CONTACT_SUCCESS: 'SEARCH_CONTACT_SUCCESS',
    SEARCH_CONTACT_ERROR: 'SEARCH_CONTACT_ERROR'
}

export default ContactAction